# Runs all containers in conjunction
version: '3'
services:
  spigot_local_build:
    build:
      context: ./spigot
    image: spigot_local:latest
    volumes: 
      - "./spigot/configs/server.properties:/root/mc/server.properties:ro,z"
      - "./spigot/configs/spigot.yml:/root/mc/spigot.yml:z"
      - "./map:/root/mc/plugins/dynmap:z"
      - "./world:/root/mc/world/"
      - "./world_nether:/root/mc/world_nether/"
      - "./world_the_end:/root/mc/world_the_end/"
      - "./spigot/configs/ops.json:/root/mc/ops.json:z"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    expose:
      - 25565
      - 8123
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z"
    expose:
      - 8082
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    